# SPDX-FileCopyrightText: 2025 MDAD project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of matrix-imessage-rustpush service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-imessage-rustpush.service"
  register: matrix_imessage_rustpush_service_stat

- when: matrix_imessage_rustpush_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-imessage-rustpush is stopped
      ansible.builtin.service:
        name: matrix-imessage-rustpush
        state: stopped
        daemon_reload: true

    - name: Ensure matrix-imessage-rustpush.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-imessage-rustpush.service"
        state: absent
