# SPDX-FileCopyrightText: 2025 MDAD project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required iMessage RustPush settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - {'name': 'matrix_imessage_rustpush_appservice_token', when: true}
    - {'name': 'matrix_imessage_rustpush_homeserver_address', when: true}
    - {'name': 'matrix_imessage_rustpush_homeserver_token', when: true}
    - {'name': 'matrix_imessage_rustpush_database_hostname', when: "{{ matrix_imessage_rustpush_database_engine == 'postgres' }}"}
    - {'name': 'matrix_imessage_rustpush_container_network', when: true}
    - {'name': 'matrix_imessage_rustpush_metrics_proxying_hostname', when: "{{ matrix_imessage_rustpush_metrics_proxying_enabled }}"}
    - {'name': 'matrix_imessage_rustpush_metrics_proxying_path_prefix', when: "{{ matrix_imessage_rustpush_metrics_proxying_enabled }}"}
