{
 "title": "Media Repo Dashboard",
 "tags": [ "matrix" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(media_http_response_time_seconds_bucket,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requsts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_http_requests_total{host=\"$host\"}[2m])",
     "legendFormat": "{{ '{{host}}: {{method}} {{action}}' }}"
    },
    {
     "expr": "rate(media_invalid_http_requests_total{host=\"$host\"}[2m])",
     "legendFormat": "{{ 'Invalid Host: {{method}} {{action}}' }}"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_http_responses_total{host=\"$host\"}[2m])",
     "legendFormat": "{{ '{{host}}: {{method}} {{action}} {{statusCode}}' }}"
    },
    {
     "expr": "rate(media_invalid_http_requests_total{host=\"$host\"}[2m])",
     "legendFormat": "{{ 'Invalid Host: {{method}} {{action}} {{statusCode}}' }}"
    }
   ]
  },
  {
   "title": "Downloads and Thumbnails - Response Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(media_http_response_time_seconds_bucket{action=~\"download|thumbnail\", host=\"$host\"}[2m])) by (le)",
     "legendFormat": "{{ '{{method}} {{action}} - {{le}}' }}"
    }
   ]
  },
  {
   "title": "Uploads - Response Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(media_http_response_time_seconds_bucket{action=\"upload\", host=\"$host\"}[2m])) by (le)",
     "legendFormat": "{{ '{{method}} {{action}} - {{le}}' }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "memory usage (alloc)" },
    { "expr": "go_memstats_sys_bytes", "legendFormat": "memory usage (sys)" },
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "heap usage (alloc)" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "heap usage (idle)" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "heap usage (used)" },
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "heap usage (released)"
    }
   ]
  },
  {
   "title": "Process Composition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "goroutines" },
    { "expr": "go_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "S3 Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_s3_operations_total[2m])",
     "legendFormat": "{{ '{{operation}}' }}"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_cache_hits_total[2m])",
     "legendFormat": "{{ 'hits in {{cache}}' }}"
    },
    {
     "expr": "rate(media_cache_misses_total[2m])",
     "legendFormat": "{{ 'misses in {{cache}}' }}"
    },
    {
     "expr": "rate(media_cache_evictions_total[2m])",
     "legendFormat": "{{ 'evictions due to {{reason}} in {{cache}}' }}"
    }
   ]
  },
  {
   "title": "Thumbnail Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_thumbnails_generated_total[2m])",
     "legendFormat": "{{ '{{origin}} {{width}}x{{height}} {{method}} animated={{animated}}' }}"
    }
   ]
  },
  {
   "title": "Age of Downloaded Media",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(media_age_accessed_media_seconds_bucket[2m])) by (le)",
     "legendFormat": "{{ '{{method}} {{action}} - {{le}}' }}"
    }
   ]
  },
  {
   "title": "Resource Handling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(media_downloaded_total[2m])",
     "legendFormat": "{{ 'downloads from {{origin}}' }}"
    },
    {
     "expr": "rate(media_url_previews_generated_total[2m])",
     "legendFormat": "{{ 'preview with engine: {{type}}' }}"
    }
   ]
  }
 ]
}