# SPDX-FileCopyrightText: 2024 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 - 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure WeChat Bridge paths exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0750'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  with_items:
    - {path: "{{ matrix_wechat_base_path }}", when: true}
    - {path: "{{ matrix_wechat_config_path }}", when: true}
    - {path: "{{ matrix_wechat_data_path }}", when: true}
    - {path: "{{ matrix_wechat_container_src_files_path }}", when: "{{ matrix_wechat_container_image_self_build }}"}
    - {path: "{{ matrix_wechat_agent_container_src_files_path }}", when: "{{ matrix_wechat_agent_container_image_self_build }}"}
  when: item.when | bool

- name: Ensure WeChat Bridge image is pulled
  community.docker.docker_image_pull:
    name: "{{ matrix_wechat_container_image }}"
    pull: always
  when: not matrix_wechat_container_image_self_build
  register: matrix_wechat_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: matrix_wechat_container_image_pull_result is not failed

- when: matrix_wechat_container_image_self_build | bool
  block:
    - name: Ensure WeChat Bridge repository is present on self-build
      ansible.builtin.git:
        repo: "{{ matrix_wechat_container_image_self_build_repo }}"
        dest: "{{ matrix_wechat_container_src_files_path }}"
        version: "{{ matrix_wechat_container_image_self_build_branch }}"
        force: "yes"
      become: true
      become_user: "{{ matrix_user_name }}"
      register: matrix_wechat_git_pull_results

    - name: Ensure WeChat Bridge container image is built
      community.docker.docker_image_build:
        name: "{{ matrix_wechat_container_image }}"
        dockerfile: Dockerfile
        path: "{{ matrix_wechat_container_src_files_path }}"
        pull: true
        rebuild: "{{ 'always' if matrix_wechat_git_pull_results.changed | bool else 'never' }}"
      register: matrix_wechat_container_image_build_result

- name: Ensure WeChat Agent image is pulled
  community.docker.docker_image_pull:
    name: "{{ matrix_wechat_agent_container_image }}"
    pull: always
  when: not matrix_wechat_agent_container_image_self_build
  register: matrix_wechat_agent_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: matrix_wechat_agent_container_image_pull_result is not failed

- when: matrix_wechat_agent_container_image_self_build | bool
  block:
    - name: Ensure WeChat Agent repository is present on self-build
      ansible.builtin.git:
        repo: "{{ matrix_wechat_agent_container_image_self_build_repo }}"
        dest: "{{ matrix_wechat_agent_container_src_files_path }}"
        version: "{{ matrix_wechat_agent_container_image_self_build_branch }}"
        force: "yes"
      become: true
      become_user: "{{ matrix_user_name }}"
      register: matrix_wechat_agent_git_pull_results

    - name: Ensure WeChat Agent container image is built
      community.docker.docker_image_build:
        name: "{{ matrix_wechat_agent_container_image }}"
        dockerfile: Dockerfile
        path: "{{ matrix_wechat_agent_container_src_files_path }}"
        pull: true
        rebuild: "{{ 'always' if matrix_wechat_agent_git_pull_results.changed | bool else 'never' }}"
      register: matrix_wechat_agent_container_image_build_result

- name: Ensure WeChat configuration installed
  ansible.builtin.copy:
    content: "{{ matrix_wechat_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ matrix_wechat_config_path }}/config.yaml"
    mode: '0644'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  register: matrix_wechat_config_result

- name: Ensure WeChat registration.yaml installed
  ansible.builtin.copy:
    content: "{{ matrix_wechat_registration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ matrix_wechat_config_path }}/registration.yaml"
    mode: '0644'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  register: matrix_wechat_registration_result

- name: Ensure Wechat Agent configuration installed
  ansible.builtin.copy:
    content: "{{ matrix_wechat_agent_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ matrix_wechat_config_path }}/agent-config.yaml"
    mode: '0644'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  register: matrix_wechat_agent_config_result

- name: Ensure matrix-wechat container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ matrix_wechat_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure matrix-wechat.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-wechat.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-wechat.service"
    mode: '0644'
  register: matrix_wechat_systemd_service_result

- name: Ensure matrix-wechat-agent.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-wechat-agent.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-wechat-agent.service"
    mode: '0644'
  register: matrix_wechat_agent_systemd_service_result

- name: Determine whether WeChat Bridge needs a restart
  ansible.builtin.set_fact:
    matrix_wechat_restart_necessary: >-
      {{
        matrix_wechat_config_result.changed | default(false)
        or matrix_wechat_registration_result.changed | default(false)
        or matrix_wechat_agent_config_result.changed | default(false)
        or matrix_wechat_systemd_service_result.changed | default(false)
        or matrix_wechat_agent_systemd_service_result.changed | default(false)
        or matrix_wechat_container_image_pull_result.changed | default(false)
        or matrix_wechat_agent_container_image_pull_result.changed | default(false)
        or matrix_wechat_container_image_build_result.changed | default(false)
        or matrix_wechat_agent_container_image_build_result.changed | default(false)
      }}
