# SPDX-FileCopyrightText: 2026 MDAD project contributors
# SPDX-FileCopyrightText: 2026 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- tags:
    - setup-all
    - setup-mautrix-gvoice
    - install-all
    - install-mautrix-gvoice
  block:
    - when: matrix_bridge_mautrix_gvoice_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_bridge_mautrix_gvoice_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

- tags:
    - setup-all
    - setup-mautrix-gvoice
  block:
    - when: not matrix_bridge_mautrix_gvoice_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
