# SPDX-FileCopyrightText: 2026 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 MDAD project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure gomuks paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0750'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  with_items:
    - {path: "{{ matrix_client_gomuks_data_path }}", when: true}
    - {path: "{{ matrix_client_gomuks_data_path }}/config", when: true}
    - {path: "{{ matrix_client_gomuks_data_path }}/logs", when: true}
    - {path: "{{ matrix_client_gomuks_data_path }}/data", when: true}
  when: "item.when | bool"

- name: Ensure gomuks container image is pulled
  community.docker.docker_image_pull:
    name: "{{ matrix_client_gomuks_container_image }}"
    pull: always
  register: matrix_client_gomuks_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: matrix_client_gomuks_container_image_pull_result is not failed

- name: Ensure gomuks configuration installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.yaml.j2"
    dest: "{{ matrix_client_gomuks_data_path }}/config/config.yaml"
    mode: '0640'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  register: matrix_client_gomuks_config_result

- name: Ensure gomuks support files installed
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ matrix_client_gomuks_data_path }}/{{ item.name }}"
    mode: '0644'
    owner: "{{ matrix_user_name }}"
    group: "{{ matrix_group_name }}"
  with_items:
    - {src: "{{ role_path }}/templates/labels.j2", name: "labels"}
    - {src: "{{ role_path }}/templates/env.j2", name: "env"}
  register: matrix_client_gomuks_support_files_result

- name: Ensure gomuks container network is created
  when: matrix_client_gomuks_container_network != 'host'
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ matrix_client_gomuks_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure matrix-client-gomuks.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-client-gomuks.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-client-gomuks.service"
    mode: '0644'
  register: matrix_client_gomuks_systemd_service_result

- name: Determine whether gomuks needs a restart
  ansible.builtin.set_fact:
    matrix_client_gomuks_restart_necessary: >-
      {{
        matrix_client_gomuks_config_result.changed | default(false)
        or matrix_client_gomuks_support_files_result.changed | default(false)
        or matrix_client_gomuks_systemd_service_result.changed | default(false)
        or matrix_client_gomuks_container_image_pull_result.changed | default(false)
      }}
