{
 "title": "Homeserver Statistics",
 "tags": [ "matrix" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "homeserver",
    "label": "Homeserver",
    "query": {
     "query": "label_values(synapse_usage_timestamp,homeserver)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "The memory usage of the process (in kilobytes on Unix-based systems, bytes on MacOS)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "synapse_usage_memory_rss{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "CPU Average Utilization (Single Core)",
   "type": "timeseries",
   "description": "CPU time in % of a single core (not % of all cores)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "synapse_usage_cpu_average{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Time Since Epoch ",
   "type": "stat",
   "description": "The current time, represented as the number of seconds since the epoch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synapse_usage_timestamp{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The number of seconds since the homeserver was last started",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synapse_usage_uptime_seconds{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "description": "The number of registered users on the homeserver",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "synapse_usage_total_users{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Total Non-bridged Users",
   "type": "timeseries",
   "description": "The number of users, excluding those created by an Application Service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "synapse_usage_total_nonbridged_users{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "timeseries",
   "description": "The total number of rooms present on the homeserver",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "synapse_usage_total_room_count{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Cache Factor",
   "type": "stat",
   "description": "The configured global factor value for caching",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synapse_usage_cache_factor{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Event Cache Size",
   "type": "stat",
   "description": "The configured event_cache_size value for caching",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synapse_usage_event_cache_size{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  { "title": "Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Daily Registered Users",
   "type": "timeseries",
   "description": "The number of native users created in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "synapse_usage_daily_user_type_native{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Registered Guest Users",
   "type": "timeseries",
   "description": "The number of guest users created in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "synapse_usage_daily_user_type_guest{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Registered Bridged Users",
   "type": "timeseries",
   "description": "The number of users created by Application Services in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "synapse_usage_daily_user_type_bridged{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "timeseries",
   "description": "The number of unique users that have used the homeserver in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "synapse_usage_daily_active_users{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Active Rooms",
   "type": "timeseries",
   "description": "The number of rooms that have had a (state) event with the type m.room.message sent in them in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "synapse_usage_daily_active_rooms{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Active E2EE Rooms",
   "type": "timeseries",
   "description": "The number of rooms that have had a (state) event with the type m.room.encrypted sent in them in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "synapse_usage_daily_active_e2ee_rooms{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Messages",
   "type": "timeseries",
   "description": "The number of (state) events with the type m.room.message seen in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "synapse_usage_daily_messages{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily E2EE Messages",
   "type": "timeseries",
   "description": "The number of (state) events sent by a local user with the type m.room.encrypted seen in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "synapse_usage_daily_e2ee_messages{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Sent Messages",
   "type": "timeseries",
   "description": "The number of (state) events sent by a local user with the type m.room.message seen in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "synapse_usage_daily_sent_messages{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Daily Sent E2EE Messages",
   "type": "timeseries",
   "description": "The number of (state) events sent by a local user with the type m.room.encrypted seen in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "synapse_usage_daily_sent_e2ee_messages{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  { "title": "Monthly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Monthly Active Users",
   "type": "timeseries",
   "description": "The number of unique users that have used the homeserver in the last 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "synapse_usage_monthly_active_users{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Monthly Retained Users",
   "type": "timeseries",
   "description": "The number of 30 day retained users, with a revised algorithm. Defined as users that appear more than once in the past 60 days, and have more than 30 days between the most and least recent appearances in the past 60 days. Includes clients that do not fit into the below r30 client types",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "synapse_usage_r30v2_users_all{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Monthly Retained Android Users",
   "type": "timeseries",
   "description": "The number of 30 day retained users, as defined above. Filtered only to clients with (\"riot\" or \"element\") and \"android\" (case-insensitive) in the user agent string",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "synapse_usage_r30v2_users_android{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Monthly Retained iOS Users",
   "type": "timeseries",
   "description": "The number of 30 day retained users, as defined above. Filtered only to clients with (\"riot\" or \"element\") and \"ios\" (case-insensitive) in the user agent string",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "synapse_usage_r30v2_users_ios{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Monthly Retained Electron Users",
   "type": "timeseries",
   "description": "The number of 30 day retained users, as defined above. Filtered only to clients with (\"riot\" or \"element\") and \"electron\" (case-insensitive) in the user agent string",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "synapse_usage_r30v2_users_electron{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  },
  {
   "title": "Monthly Retained Web Users",
   "type": "timeseries",
   "description": "The number of 30 day retained users, as defined above. Filtered only to clients with \"mozilla\" or \"gecko\" (case-insensitive) in the user agent string",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "synapse_usage_r30v2_users_web{homeserver=~\"$homeserver\"}",
     "legendFormat": "{{homeserver}}"
    }
   ]
  }
 ]
}