# SPDX-FileCopyrightText: 2026 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Include roles for mautrix-linkedin Molecule tests
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../molecule-shared/playbook-context.yml"
  gather_facts: true
  tasks:
    - name: Include roles for mautrix-linkedin Molecule tests
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        public: true
      loop:
        - com.devture.ansible.role.playbook_help
        - com.devture.ansible.role.systemd_docker_base
        - "custom/{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      loop_control:
        loop_var: role_name

- name: Ensure mautrix-linkedin is started
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure systemd daemon is reloaded
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Ensure the mautrix-linkedin systemd service is started
      ansible.builtin.systemd_service:
        name: matrix-mautrix-linkedin.service
        state: started
