# SPDX-FileCopyrightText: 2020 - 2022 Slavi Pantaleev
# SPDX-FileCopyrightText: 2022 Marko Weltzer
# SPDX-FileCopyrightText: 2026 Chiu Ki Sit
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check for Synology DSM
  ansible.builtin.stat:
    path: /etc/synoinfo.conf
  register: matrix_synoinfo_conf_stat

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_matrix_user_synology.yml"
  when: matrix_synoinfo_conf_stat.stat.exists | bool

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_matrix_user_linux.yml"
  when: not (matrix_synoinfo_conf_stat.stat.exists | bool)
