# SPDX-FileCopyrightText: 2026 Chiu Ki Sit
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure requests Python package is pinned for Docker SDK compatibility (Synology)
  ansible.builtin.pip:
    name: requests==2.31.0
    state: present

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_synology_boot_fix.yml"
