# SPDX-FileCopyrightText: 2021 Yannick Goossens
# SPDX-FileCopyrightText: 2022 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if there's not at least 1 client
  ansible.builtin.fail:
    msg: >-
      You need at least 1 client in the matrix_bot_go_neb_clients block.
  when: matrix_bot_go_neb_clients is not defined or matrix_bot_go_neb_clients[0] is not defined

- name: Fail if there's not at least 1 service
  ansible.builtin.fail:
    msg: >-
      You need at least 1 service in the matrix_bot_go_neb_services block.
  when: matrix_bot_go_neb_services is not defined or matrix_bot_go_neb_services[0] is not defined

- name: (Deprecation) Catch and report renamed matrix-bot-go-neb variables
  ansible.builtin.fail:
    msg: >-
      The variable `{{ item.old }}` is deprecated. Please use `{{ item.new }}` instead.
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - {'old': 'matrix_bot_go_neb_container_image_force_pull', 'new': '<removed> (the new community.docker.docker_image_pull module handles this natively)'}
