# SPDX-FileCopyrightText: 2026 MDAD project contributors
# SPDX-FileCopyrightText: 2026 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of matrix-tuwunel service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-tuwunel.service"
  register: matrix_tuwunel_service_stat

- when: matrix_tuwunel_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-tuwunel is stopped
      ansible.builtin.systemd:
        name: matrix-tuwunel
        state: stopped
        daemon_reload: true

    - name: Ensure matrix-tuwunel.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-tuwunel.service"
        state: absent
